name: yaru_window_decoration
description: An experimental Flutter plugin to create modern looking window decorations (rounded corners, light window border) on Linux, without libhandy.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaru_window: ^0.1.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/style.css
    - assets/style-dark.css
  plugin:
    platforms:
      linux:
        pluginClass: YaruWindowDecorationPlugin

platforms:
  linux:
